# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Co < Formula
  desc ""
  homepage ""
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/pkshimizu/co/releases/download/v0.1.4/co_Darwin_x86_64.tar.gz"
      sha256 "49e0d7cf47946038ee7528e98f58efd02ba772d25906707f0064469715e69be2"

      def install
        bin.install "co"
      end
    end
    on_arm do
      url "https://github.com/pkshimizu/co/releases/download/v0.1.4/co_Darwin_arm64.tar.gz"
      sha256 "5544c55ff8db0341d3f2d56e8b06b49326bffd550dac0c96084eae55cfeb62b7"

      def install
        bin.install "co"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pkshimizu/co/releases/download/v0.1.4/co_Linux_x86_64.tar.gz"
        sha256 "486cdd1372d8eeb80efdb945af21fc110fb9ec08cfd0b5586f883e8ca71dadf2"

        def install
          bin.install "co"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pkshimizu/co/releases/download/v0.1.4/co_Linux_arm64.tar.gz"
        sha256 "af04dc8bec4b3ce53d191d415b27b47b3ebd40d9c7d3eae2fe12a1a05beca367"

        def install
          bin.install "co"
        end
      end
    end
  end
end
