# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Do < Formula
  desc ""
  homepage ""
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/pkshimizu/do/releases/download/v0.1.3/do_Darwin_x86_64.tar.gz"
      sha256 "ac54a1738281095b075f3d8a8d0e475853c386a95ddea1783cc516082e3e1f85"

      def install
        bin.install "do"
      end
    end
    on_arm do
      url "https://github.com/pkshimizu/do/releases/download/v0.1.3/do_Darwin_arm64.tar.gz"
      sha256 "2d14e540c0f36f2b185b566035bacae1e9dbf11273b357d4570ad5ae62a789e3"

      def install
        bin.install "do"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pkshimizu/do/releases/download/v0.1.3/do_Linux_x86_64.tar.gz"
        sha256 "9bb1527825be294c9678dc3a3cd78f8877e4198dd0d8d6c55cbc110268b88feb"

        def install
          bin.install "do"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pkshimizu/do/releases/download/v0.1.3/do_Linux_arm64.tar.gz"
        sha256 "31adc74270d9486721298152dc602d13a847d29de8c25354d8780780db867ba1"

        def install
          bin.install "do"
        end
      end
    end
  end
end
