# typed: false
# frozen_string_literal: true

# This file is generated by the fv release workflow. DO NOT EDIT.
class Fv < Formula
  desc "TUI file viewer/manager built on a Component Architecture"
  homepage "https://github.com/pkshimizu/fv"
  version "0.1.3"

  on_macos do
    on_arm do
      url "https://github.com/pkshimizu/fv/releases/download/v0.1.3/fv-aarch64-apple-darwin.tar.gz"
      sha256 "7480e60846106057c12dc0aed27b51b72ae7c7df4c1fd3903bec0cc64e65649a"

      def install
        bin.install "fv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pkshimizu/fv/releases/download/v0.1.3/fv-x86_64-unknown-linux-gnu.tar.gz"
        sha256 "0b740209f7cf0ac77d33ec4d32efe717952e7509da6f3a9f137a42ec74ce4423"

        def install
          bin.install "fv"
        end
      end
    end
  end
end
