# typed: false
# frozen_string_literal: true

# This file is generated by the fv release workflow. DO NOT EDIT.
class Fv < Formula
  desc "TUI file viewer/manager built on a Component Architecture"
  homepage "https://github.com/pkshimizu/fv"
  version "0.1.2"

  on_macos do
    on_arm do
      url "https://github.com/pkshimizu/fv/releases/download/v0.1.2/fv-aarch64-apple-darwin.tar.gz"
      sha256 "d780e538ee169c65c47760961f1aae6fd6bdf7e73ff943f5f4f1806435a83324"

      def install
        bin.install "fv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pkshimizu/fv/releases/download/v0.1.2/fv-x86_64-unknown-linux-gnu.tar.gz"
        sha256 "8172d7e98d515b35ce1628423effda3c3c27e5ed9b6dbb1bcaaf20bb75931e1c"

        def install
          bin.install "fv"
        end
      end
    end
  end
end
